### ISSUE TITLE
EMA error

### ISSUE THREAD

**Issue by liguopeng0923** [Hao840/OFAKD#20]
Hi @Hao840 ,

There may be some issues with EMA.
<img width="764" alt="image" src="https://github.com/Hao840/OFAKD/assets/61257834/038f3e0a-37f5-4bc0-a5b2-d5b61b26271e">

**Comment by Hao840** [comment]
it has been fixed.

**Comment by liguopeng0923** [comment]
Thanks !!😄

**Comment by liguopeng0923** [comment]
Hi @Hao840 ,

I reproduced the results, but the ema is still not normal.

<img width="1135" alt="image" src="https://github.com/Hao840/OFAKD/assets/61257834/bbd74750-9076-472f-9684-502ad6944d7c">

**Comment by Hao840** [comment]
EMA works poorly on cifar because of insufficient number of iterations. So we didn't use it on this dataset. You will get normal results on ImageNet.

**Comment by liguopeng0923** [comment]
Thanks! I get it.
